name: format
on:
  push:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install formatter dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: Format with black
        run: |
          black jupyddl tests
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Apply formatting changes
          branch: main
